[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
tokio-util.workspace = true
bytes.workspace = true
shlex.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
uuid.workspace = true
ts-rs.workspace = true
rust-embed.workspace = true
directories.workspace = true
open.workspace = true
regex.workspace = true
json-patch.workspace = true
jsonwebtoken.workspace = true
tokio.workspace = true
futures.workspace = true
tokio-stream.workspace = true
shellexpand.workspace = true
which.workspace = true
similar.workspace = true
dirs.workspace = true
thiserror.workspace = true
command-group.workspace = true
anyhow.workspace = true
reqwest.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal", "process"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows-sys = { version = "0.61", features = ["Win32_System_Environment"] }
